export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions With Zero Fees',
    description: 'Get Access To Our Exclusive App That Allows Your To Send Unlimited Transactions Without Getting Charged Any Fees.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-5.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Login To Your Account At Any Time',
    description: 'We Have You Covered No Matter Where You Are Located. All You Need Is An Internet Connection And a Phone Or Computer.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/svg-6.svg').default,
    alt: 'PiggyBank',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join Our Team',
    headline: 'Creating An Account Is Extremely Easy',
    description: 'Get Everything Set Up And Ready In Under 10Min. All You Need To Do Is Add Your Information And You Are Ready To Go',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/svg-7.svg').default,
    alt: 'Papers',
    dark: false,
    primary: false,
    darkText: true,
};